// Package networkd configures IP addressing through systemd-networkd.
package networkd

import (
	"bufio"
	"context"
	"errors"
	"net/netip"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"netcfg/internal/adapters/sysexec"
	"netcfg/internal/domain"
	"netcfg/internal/platform/fileutil"
)

// DefaultDir is where systemd-networkd looks for unit files.
const DefaultDir = "/etc/systemd/network"

const header = "# Generated by netcfgd. Manual edits will be overwritten.\n"

// Backend implements ports.IPBackend.
type Backend struct {
	dir string
}

func New(dir string) *Backend {
	if dir == "" {
		dir = DefaultDir
	}
	return &Backend{dir: dir}
}

func (b *Backend) Kind() domain.BackendKind { return domain.BackendNetworkd }

// Detect returns the links networkd currently manages.
func (b *Backend) Detect(ctx context.Context) ([]string, error) {
	if !sysexec.Available("networkctl") {
		return nil, domain.Unavailable("networkctl is not installed")
	}
	if out, err := sysexec.Run(ctx, "systemctl", "is-active", "systemd-networkd"); err != nil ||
		strings.TrimSpace(out) != "active" {
		return nil, domain.Unavailable("systemd-networkd is not running")
	}

	out, err := sysexec.Run(ctx, "networkctl", "list", "--no-legend", "--no-pager")
	if err != nil {
		return nil, err
	}

	var links []string
	for _, line := range strings.Split(out, "\n") {
		fields := strings.Fields(line)
		// IDX LINK TYPE OPERATIONAL SETUP
		if len(fields) < 5 || fields[2] == "loopback" || fields[4] == "unmanaged" {
			continue
		}
		if domain.ValidateLinkName(fields[1]) == nil {
			links = append(links, fields[1])
		}
	}
	return links, nil
}

// path returns the unit file that governs a link. networkd obeys the first
// file whose [Match] accepts the interface in lexicographic order, so an
// existing file has to be edited in place: writing a new 10-<link>.network
// beside a 20-<link>.network would shadow it and silently drop its settings.
func (b *Backend) path(link string) (string, error) {
	if err := domain.ValidateLinkName(link); err != nil {
		return "", err
	}
	if found := b.existing(link); found != "" {
		return found, nil
	}
	return filepath.Join(b.dir, "10-"+link+".network"), nil
}

func (b *Backend) existing(link string) string {
	entries, err := os.ReadDir(b.dir)
	if err != nil {
		return ""
	}

	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".network") {
			names = append(names, e.Name())
		}
	}
	slices.Sort(names)

	for _, name := range names {
		full := filepath.Join(b.dir, name)
		if matchesLink(full, link) {
			return full
		}
	}
	return ""
}

// matchesLink reports whether a unit file's [Match] Name= list covers link.
func matchesLink(path, link string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	var inMatch, hit bool
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "[") {
			inMatch = strings.EqualFold(line, "[Match]")
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !inMatch || !ok || !strings.EqualFold(strings.TrimSpace(key), "Name") {
			continue
		}
		for _, pattern := range strings.Fields(value) {
			// A negated pattern excludes the link outright.
			if rest, negated := strings.CutPrefix(pattern, "!"); negated {
				if matched, _ := filepath.Match(rest, link); matched {
					return false
				}
				continue
			}
			if matched, _ := filepath.Match(pattern, link); matched {
				hit = true
			}
		}
	}
	return hit
}

// Current reads back the unit file this app owns.
func (b *Backend) Current(ctx context.Context, link string) (domain.IPPlan, error) {
	plan := domain.IPPlan{Link: link, Mode: domain.ModeDHCP, Mode6: domain.ModeAuto}
	path, err := b.path(link)
	if err != nil {
		return plan, err
	}

	f, err := os.Open(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return plan, nil
		}
		return plan, domain.Internal("read %s: %v", path, err)
	}
	defer f.Close()

	var sawStaticV4, sawStaticV6 bool
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "[") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key, value = strings.TrimSpace(key), strings.TrimSpace(value)

		switch key {
		case "DHCP":
			if value == "no" || value == "ipv6" {
				plan.Mode = domain.ModeDisabled
			}
		case "Address":
			if isV4(value) {
				sawStaticV4 = true
				plan.Address = value
			} else {
				sawStaticV6 = true
				plan.Address6 = value
			}
		case "Gateway":
			if isV4(value) {
				plan.Gateway = value
			} else {
				plan.Gateway6 = value
			}
		case "IPv6AcceptRA":
			if strings.EqualFold(value, "no") {
				plan.Mode6 = domain.ModeDisabled
			}
		case "LinkLocalAddressing":
			if value == "ipv4" || value == "no" {
				plan.Mode6 = domain.ModeDisabled
			}
		case "RouteMetric", "Metric":
			if parsed, err := strconv.ParseUint(value, 10, 32); err == nil {
				plan.Metric = uint32(parsed)
			}
		case "UseGateway", "DefaultRouteOnDevice":
			if strings.EqualFold(value, "no") {
				plan.NoDefaultRoute = true
			}
		case "DNS":
			plan.DNS = append(plan.DNS, value)
		}
	}
	if sawStaticV4 {
		plan.Mode = domain.ModeStatic
	}
	if sawStaticV6 {
		plan.Mode6 = domain.ModeStatic
	}
	return plan, sc.Err()
}

// Apply writes the unit file and reloads networkd.
func (b *Backend) Apply(ctx context.Context, plan domain.IPPlan) error {
	normalized, err := plan.Normalize()
	if err != nil {
		return err
	}
	path, err := b.path(normalized.Link)
	if err != nil {
		return err
	}
	if err := fileutil.WriteAtomic(path, render(normalized), 0o644); err != nil {
		return err
	}
	if _, err := sysexec.Run(ctx, "networkctl", "reload"); err != nil {
		return err
	}
	_, err = sysexec.Run(ctx, "networkctl", "reconfigure", normalized.Link)
	return err
}

func render(plan domain.IPPlan) []byte {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("[Match]\nName=" + plan.Link + "\n\n[Network]\n")

	b.WriteString("DHCP=" + dhcpValue(plan) + "\n")

	if plan.Mode6 == domain.ModeAuto {
		b.WriteString("IPv6AcceptRA=yes\n")
	} else {
		b.WriteString("IPv6AcceptRA=no\n")
	}
	if plan.Mode6 == domain.ModeDisabled {
		// Also removes the link-local address, which is what disabling IPv6 means.
		b.WriteString("LinkLocalAddressing=ipv4\n")
	}

	if plan.Mode == domain.ModeStatic {
		b.WriteString("Address=" + plan.Address + "\n")
	}
	if plan.Mode6 == domain.ModeStatic {
		b.WriteString("Address=" + plan.Address6 + "\n")
	}
	// [Network] Gateway= cannot carry a metric, so a metered static default
	// route has to be expressed as a [Route] section instead.
	if plan.Metric == 0 {
		if plan.Gateway != "" {
			b.WriteString("Gateway=" + plan.Gateway + "\n")
		}
		if plan.Gateway6 != "" {
			b.WriteString("Gateway=" + plan.Gateway6 + "\n")
		}
	}
	for _, dns := range plan.DNS {
		b.WriteString("DNS=" + dns + "\n")
	}

	if plan.Mode == domain.ModeDHCP && len(plan.DNS) > 0 {
		b.WriteString("\n[DHCP]\nUseDNS=no\n")
	}

	if plan.Metric > 0 || plan.NoDefaultRoute {
		metric := strconv.FormatUint(uint64(plan.Metric), 10)
		if plan.Mode == domain.ModeDHCP {
			b.WriteString("\n[DHCPv4]\n")
			if plan.Metric > 0 {
				b.WriteString("RouteMetric=" + metric + "\n")
			}
			if plan.NoDefaultRoute {
				b.WriteString("UseGateway=no\n")
			}
		}
		if plan.Mode6 == domain.ModeAuto {
			b.WriteString("\n[IPv6AcceptRA]\n")
			if plan.Metric > 0 {
				b.WriteString("RouteMetric=" + metric + "\n")
			}
			if plan.NoDefaultRoute {
				b.WriteString("UseGateway=no\n")
			}
		}
		if plan.Metric > 0 {
			for _, gateway := range []string{plan.Gateway, plan.Gateway6} {
				if gateway != "" {
					b.WriteString("\n[Route]\nGateway=" + gateway + "\nMetric=" + metric + "\n")
				}
			}
		}
	}
	return []byte(b.String())
}

// dhcpValue maps the two per-family modes onto networkd's single DHCP= key.
func dhcpValue(plan domain.IPPlan) string {
	wantV4 := plan.Mode == domain.ModeDHCP
	// SLAAC is handled by IPv6AcceptRA; DHCPv6 is requested by the router's RA
	// flags, so DHCP= only has to describe IPv4 here.
	if wantV4 {
		return "ipv4"
	}
	return "no"
}

func isV4(value string) bool {
	if prefix, err := netip.ParsePrefix(value); err == nil {
		return prefix.Addr().Is4()
	}
	addr, err := netip.ParseAddr(value)
	return err == nil && addr.Is4()
}
