// Package ifupdown configures IP addressing through Debian's classic
// /etc/network/interfaces.d drop-in directory.
package ifupdown

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"netcfg/internal/adapters/sysexec"
	"netcfg/internal/domain"
	"netcfg/internal/platform/fileutil"
)

const (
	// DefaultDir is the drop-in directory sourced by /etc/network/interfaces.
	DefaultDir = "/etc/network/interfaces.d"
	mainFile   = "/etc/network/interfaces"
	header     = "# Generated by netcfgd. Manual edits will be overwritten.\n"
)

// Backend implements ports.IPBackend.
type Backend struct {
	dir  string
	main string
}

func New(dir string) *Backend {
	if dir == "" {
		dir = DefaultDir
	}
	return &Backend{dir: dir, main: mainFile}
}

func (b *Backend) Kind() domain.BackendKind { return domain.BackendIfupdown }

// Detect requires both the tooling and a drop-in directory that is sourced.
func (b *Backend) Detect(ctx context.Context) ([]string, error) {
	if !sysexec.Available("ifup") {
		return nil, domain.Unavailable("ifupdown is not installed")
	}
	if _, err := os.Stat(b.main); err != nil {
		return nil, domain.Unavailable("%s not found", b.main)
	}
	if !b.sourcesDropIn() {
		return nil, domain.Unavailable("%s is missing the line \"source /etc/network/interfaces.d/*\"", b.main)
	}

	links := b.declaredIn(b.main)
	if entries, err := os.ReadDir(b.dir); err == nil {
		for _, e := range entries {
			if !e.IsDir() && domain.ValidateLinkName(e.Name()) == nil {
				links = append(links, e.Name())
			}
		}
	}
	return links, nil
}

func (b *Backend) sourcesDropIn() bool {
	f, err := os.Open(b.main)
	if err != nil {
		return false
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "source") && strings.Contains(line, "interfaces.d") {
			return true
		}
	}
	return false
}

func (b *Backend) declaredIn(path string) []string {
	f, err := os.Open(path)
	if err != nil {
		return nil
	}
	defer f.Close()

	var out []string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) >= 2 && fields[0] == "iface" && fields[1] != "lo" &&
			domain.ValidateLinkName(fields[1]) == nil {
			out = append(out, fields[1])
		}
	}
	return out
}

func (b *Backend) path(link string) (string, error) {
	if err := domain.ValidateLinkName(link); err != nil {
		return "", err
	}
	return filepath.Join(b.dir, link), nil
}

// Current parses the drop-in file this app owns.
func (b *Backend) Current(ctx context.Context, link string) (domain.IPPlan, error) {
	plan := domain.IPPlan{Link: link, Mode: domain.ModeDHCP, Mode6: domain.ModeAuto}
	path, err := b.path(link)
	if err != nil {
		return plan, err
	}

	f, err := os.Open(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return plan, nil
		}
		return plan, domain.Internal("read %s: %v", path, err)
	}
	defer f.Close()

	family := "inet"
	var address, netmask string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) < 2 {
			continue
		}
		switch fields[0] {
		case "iface":
			if len(fields) < 4 {
				continue
			}
			family = fields[2]
			mode := fields[3]
			if family == "inet6" {
				plan.Mode6 = mapMode6(mode)
			} else {
				plan.Mode = mapMode4(mode)
			}
		case "address":
			if family == "inet6" {
				plan.Address6 = fields[1]
			} else {
				address = fields[1]
			}
		case "netmask":
			netmask = fields[1]
		case "gateway":
			if family == "inet6" {
				plan.Gateway6 = fields[1]
			} else {
				plan.Gateway = fields[1]
			}
		case "dns-nameservers":
			plan.DNS = append(plan.DNS, fields[1:]...)
		case "metric":
			if parsed, err := strconv.ParseUint(fields[1], 10, 32); err == nil {
				plan.Metric = uint32(parsed)
			}
		}
	}

	if address != "" {
		plan.Address = address
		if !strings.Contains(address, "/") && netmask != "" {
			if bits, err := maskToBits(netmask); err == nil {
				plan.Address = fmt.Sprintf("%s/%d", address, bits)
			}
		}
	}
	return plan, sc.Err()
}

// Apply rewrites the drop-in stanza and cycles the interface.
func (b *Backend) Apply(ctx context.Context, plan domain.IPPlan) error {
	normalized, err := plan.Normalize()
	if err != nil {
		return err
	}
	// A static stanza simply omits the gateway, but ifupdown has no way to tell
	// the DHCP client to discard the offered default route.
	if normalized.NoDefaultRoute && normalized.Mode == domain.ModeDHCP {
		return domain.Invalid("ifupdown cannot suppress the default route offered by DHCP on %s; use a static address instead", normalized.Link)
	}
	path, err := b.path(normalized.Link)
	if err != nil {
		return err
	}
	if err := fileutil.WriteAtomic(path, render(normalized), 0o644); err != nil {
		return err
	}

	// ifdown may legitimately fail when the interface is already down.
	_, _ = sysexec.Run(ctx, "ifdown", "--force", normalized.Link)
	_, err = sysexec.Run(ctx, "ifup", normalized.Link)
	return err
}

func render(plan domain.IPPlan) []byte {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("auto " + plan.Link + "\n\n")

	switch plan.Mode {
	case domain.ModeDHCP:
		b.WriteString("iface " + plan.Link + " inet dhcp\n")
		writeMetric(&b, plan)
		writeDNS(&b, plan)
	case domain.ModeStatic:
		prefix := netip.MustParsePrefix(plan.Address)
		b.WriteString("iface " + plan.Link + " inet static\n")
		b.WriteString("    address " + prefix.Addr().String() + "\n")
		b.WriteString("    netmask " + bitsToMask(prefix.Bits()) + "\n")
		if plan.Gateway != "" {
			b.WriteString("    gateway " + plan.Gateway + "\n")
		}
		writeMetric(&b, plan)
		writeDNS(&b, plan)
	case domain.ModeDisabled:
		b.WriteString("iface " + plan.Link + " inet manual\n")
	}

	switch plan.Mode6 {
	case domain.ModeAuto:
		b.WriteString("\niface " + plan.Link + " inet6 auto\n")
		writeMetric(&b, plan)
	case domain.ModeStatic:
		b.WriteString("\niface " + plan.Link + " inet6 static\n")
		b.WriteString("    address " + plan.Address6 + "\n")
		if plan.Gateway6 != "" {
			b.WriteString("    gateway " + plan.Gateway6 + "\n")
		}
		writeMetric(&b, plan)
		if plan.Mode == domain.ModeDisabled {
			writeDNS(&b, plan)
		}
	case domain.ModeDisabled:
		b.WriteString("\niface " + plan.Link + " inet6 manual\n")
		b.WriteString("    autoconf 0\n")
		b.WriteString("    accept_ra 0\n")
	}
	return []byte(b.String())
}

func writeDNS(b *strings.Builder, plan domain.IPPlan) {
	if len(plan.DNS) > 0 {
		b.WriteString("    dns-nameservers " + strings.Join(plan.DNS, " ") + "\n")
	}
}

func writeMetric(b *strings.Builder, plan domain.IPPlan) {
	if plan.Metric > 0 {
		b.WriteString("    metric " + strconv.FormatUint(uint64(plan.Metric), 10) + "\n")
	}
}

func mapMode4(mode string) domain.Mode {
	switch mode {
	case "static":
		return domain.ModeStatic
	case "manual":
		return domain.ModeDisabled
	default:
		return domain.ModeDHCP
	}
}

func mapMode6(mode string) domain.Mode {
	switch mode {
	case "static":
		return domain.ModeStatic
	case "manual":
		return domain.ModeDisabled
	default:
		return domain.ModeAuto
	}
}

func bitsToMask(bits int) string {
	var mask [4]byte
	for i := 0; i < bits && i < 32; i++ {
		mask[i/8] |= 1 << uint(7-i%8)
	}
	return netip.AddrFrom4(mask).String()
}

func maskToBits(mask string) (int, error) {
	addr, err := netip.ParseAddr(mask)
	if err != nil || !addr.Is4() {
		return 0, fmt.Errorf("invalid netmask: %q", mask)
	}
	bits := 0
	for _, b := range addr.As4() {
		for i := 7; i >= 0; i-- {
			if b&(1<<uint(i)) != 0 {
				bits++
			}
		}
	}
	return bits, nil
}
